export const GLOBAL_ACHIEVEMENTS = {
  ANCIENT_TECHNOLOGY_1: 'Ancient Technology 1',
  ANCIENT_TECHNOLOGY_2: 'Ancient Technology 2',
  ANCIENT_TECHNOLOGY_3: 'Ancient Technology 3',
  ANCIENT_TECHNOLOGY_4: 'Ancient Technology 4',
  ANCIENT_TECHNOLOGY_5: 'Ancient Technology 5',
  ANNIHILATION_OF_THE_ORDER: 'Annihilation of the Order',
  ARTIFACT_RECOVERED: 'Artifact: Recovered',
  ARTIFACT_LOST: 'Artifact: Lost',
  ARTIFACT_CLEANSED: 'Artifact: Cleansed',
  CITY_RULE_MILITARISTIC: 'City Rule: Militaristic',
  CITY_RULE_ECONOMIC: 'City Rule: Economic',
  CITY_RULE_DEMONIC: 'City Rule: Demonic',
  END_OF_THE_INVASION: 'End of the Invasion',
  END_OF_CORRUPTION_1: 'End of Corruption 1',
  END_OF_CORRUPTION_2: 'End of Corruption 2',
  END_OF_CORRUPTION_3: 'End of Corruption 3',
  END_OF_GLOOM: 'End of Gloom',
  THE_DRAKE_SLAIN: 'The Drake Slain',
  THE_DRAKE_AIDED: 'The Drake Aided',
  THE_DEAD_INVADE: 'The Dead Invade',
  THE_DEMON_DETHRONED: 'The Demon Dethroned',
  THE_EDGE_OF_DARKNESS: 'The Edge of Darkness',
  THE_MERCHANT_FLEES: 'The Merchant Flees',
  THE_POWER_OF_ENHANCEMENT: 'The Power of Enhancement',
  THE_RIFT_CLOSED: 'The Rift Closed',
  THE_RIFT_NEUTRALIZED: 'The Rift Neutralized',
  THE_VOICE_SILENCED: 'The Voice: Silenced',
  THE_VOICE_FREED: 'The Voice: Freed',
  WATER_BREATHING: 'Water-Breathing',
};
