export const ICONS = {
  elementAir: '../../assets/images/icons/elements/element-small-air.png',
  elementAll: '../../assets/images/icons/elements/element-small-all.png',
  elementConsume: '../../assets/images/icons/elements/element-small-consume.png',
  elementDark: '../../assets/images/icons/elements/element-small-dark.png',
  elementEarth: '../../assets/images/icons/elements/element-small-earth.png',
  elementFire: '../../assets/images/icons/elements/element-small-fire.png',
  elementIce: '../../assets/images/icons/elements/element-small-ice.png',
  elementLight: '../../assets/images/icons/elements/element-small-light.png',

  statusEffectAddTarget: '../../assets/images/icons/status-effect/status-effect-small-add-target.png',
  statusEffectBless: '../../assets/images/icons/status-effect/status-effect-small-bless.png',
  statusEffectCurse: '../../assets/images/icons/status-effect/status-effect-small-curse.png',
  statusEffectDisarm: '../../assets/images/icons/status-effect/status-effect-small-disarm.png',
  statusEffectImmobilize: '../../assets/images/icons/status-effect/status-effect-small-immobilize.png',
  statusEffectInvisible: '../../assets/images/icons/status-effect/status-effect-small-invisible.png',
  statusEffectMuddle: '../../assets/images/icons/status-effect/status-effect-small-muddle.png',
  statusEffectPierce: '../../assets/images/icons/status-effect/status-effect-small-pierce.png',
  statusEffectPoison: '../../assets/images/icons/status-effect/status-effect-small-poison.png',
  statusEffectPush: '../../assets/images/icons/status-effect/status-effect-small-push.png',
  statusEffectPull: '../../assets/images/icons/status-effect/status-effect-small-pull.png',
  statusEffectStrengthen: '../../assets/images/icons/status-effect/status-effect-small-strengthen.png',
  statusEffectStun: '../../assets/images/icons/status-effect/status-effect-small-stun.png',
  statusEffectWound: '../../assets/images/icons/status-effect/status-effect-small-wound.png',

  generalAttack: '../../assets/images/icons/general/general-small-attack.png',
  generalAttackHex: '../../assets/images/icons/general/general-small-attack-hex.png',
  generalHeal: '../../assets/images/icons/general/general-small-heal.png',
  generalJump: '../../assets/images/icons/general/general-small-jump.png',
  generalLoot: '../../assets/images/icons/general/general-small-loot.png',
  generalMove: '../../assets/images/icons/general/general-small-move.png',
  generalRange: '../../assets/images/icons/general/general-small-range.png',
  generalRetaliate: '../../assets/images/icons/general/general-small-retaliate.png',
  generalShield: '../../assets/images/icons/general/general-small-shield.png',
  generalTarget: '../../assets/images/icons/general/general-small-target.png',
  generalPlusOne: '../../assets/images/icons/general/general-small-plus-one.png',

  // brute: '../../assets/images/icons/classes/brute.svg',
  // spellweaver: '../../assets/images/icons/classes/spellweaver.svg',
  // cragheart: '../../assets/images/icons/classes/cragheart.svg',
  // scoundrel: '../../assets/images/icons/classes/scoundrel.svg',
  // mindthief: '../../assets/images/icons/classes/mindthief.svg',
  // tinkerer: '../../assets/images/icons/classes/tinkerer.svg',
  // bear: '../../assets/images/icons/classes/bear.svg',
  // circles: '../../assets/images/icons/classes/circles.svg',
  // cuthulu: '../../assets/images/icons/classes/cuthulu.svg',
  // eclipse: '../../assets/images/icons/classes/eclipse.svg',
  // lightning: '../../assets/images/icons/classes/lightning.svg',
  // mask: '../../assets/images/icons/general/classes/mask.svg',
  // musicNote: '../../assets/images/icons/classes/music_note.svg',
  // saw: '../../assets/images/icons/classes/saw.svg',
  // sun: '../../assets/images/icons/classes/sun.svg',
  // triSpear: '../../assets/images/icons/classes/tri_spear.svg',
  // triforce: '../../assets/images/icons/classes/triforce.svg',
};
