export const ICONS = {
  elementAir: '../../../assets/images/icons/elements/element-small-air.png',
  elementAll: '../../images/icons/elements/element-small-all.png',
  elementConsume: '../../images/icons/elements/element-small-consume.png',
  elementDark: '../../images/icons/elements/element-small-dark.png',
  elementEarth: '../../images/icons/elements/element-small-earth.png',
  elementFire: '../../images/icons/elements/element-small-fire.png',
  elementIce: '../../images/icons/elements/element-small-ice.png',
  elementLight: '../../images/icons/elements/element-small-light.png',

  statusEffectAddTarget: '../../images/icons/status-effect/status-effect-small-add-target.png',
  statusEffectBless: '../../images/icons/status-effect/status-effect-small-bless.png',
  statusEffectCurse: '../../images/icons/status-effect/status-effect-small-curse.png',
  statusEffectDisarm: '../../images/icons/status-effect/status-effect-small-disarm.png',
  statusEffectImmobilize: '../../images/icons/status-effect/status-effect-small-immobilize.png',
  statusEffectInvisible: '../../images/icons/status-effect/status-effect-small-invisible.png',
  statusEffectMuddle: '../../images/icons/status-effect/status-effect-small-muddle.png',
  statusEffectPierce: '../../images/icons/status-effect/status-effect-small-pierce.png',
  statusEffectPoison: '../../images/icons/status-effect/status-effect-small-poison.png',
  statusEffectPush: '../../images/icons/status-effect/status-effect-small-push.png',
  statusEffectPull: '../../images/icons/status-effect/status-effect-small-pull.png',
  statusEffectStrengthen: '../../images/icons/status-effect/status-effect-small-strengthen.png',
  statusEffectStun: '../../images/icons/status-effect/status-effect-small-stun.png',
  statusEffectWound: '../../images/icons/status-effect/status-effect-small-wound.png',

  generalAttack: '../../images/icons/general/general-small-attack.png',
  generalAttackHex: '../../images/icons/general/general-small-attack-hex.png',
  generalHeal: '../../images/icons/general/general-small-heal.png',
  generalJump: '../../images/icons/general/general-small-jump.png',
  generalLoot: '../../images/icons/general/general-small-loot.png',
  generalMove: '../../images/icons/general/general-small-move.png',
  generalRange: '../../images/icons/general/general-small-range.png',
  generalRetaliate: '../../images/icons/general/general-small-retaliate.png',
  generalShield: '../../images/icons/general/general-small-shield.png',
  generalTarget: '../../images/icons/general/general-small-target.png',
  generalPlusOne: '../../images/icons/general/general-small-plus-one.png',
};
